namespace dot_net_server.Helpers;

public static class PasswordHelper
{
    /// <summary>
    /// Hash a password using BCrypt with 10 work rounds.
    /// Compatible with Node.js bcryptjs hashes.
    /// </summary>
    public static string HashPassword(string password)
    {
        return BCrypt.Net.BCrypt.HashPassword(password, workFactor: 10);
    }

    /// <summary>
    /// Verify a password against a stored BCrypt hash.
    /// Works with hashes generated by both .NET and Node.js bcryptjs.
    /// </summary>
    public static bool VerifyPassword(string password, string storedHash)
    {
        return BCrypt.Net.BCrypt.Verify(password, storedHash);
    }
}